/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brama Hendra Mahendra
 */
public class ViewMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form ViewMahasiswa
     */
    public ViewMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_nim = new javax.swing.JTextField();
        jTextField_nama = new javax.swing.JTextField();
        jComboBox_jurusan = new javax.swing.JComboBox<>();
        jRadioButton_laki = new javax.swing.JRadioButton();
        jRadioButton_perempuan = new javax.swing.JRadioButton();
        jButton_tambah = new javax.swing.JButton();
        jButton_hapus = new javax.swing.JButton();
        jButton_ubah = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_cari = new javax.swing.JTextField();
        jButton_cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_datamahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Jurursan");

        jLabel4.setText("Jenis Kelamin");

        jComboBox_jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatika", "Teknologi Informasi", " " }));

        jenisKelamin.add(jRadioButton_laki);
        jRadioButton_laki.setText("Laki-Laki");

        jenisKelamin.add(jRadioButton_perempuan);
        jRadioButton_perempuan.setText("Perempuan");

        jButton_tambah.setText("Tambah");

        jButton_hapus.setText("Hapus");

        jButton_ubah.setText("Ubah");

        jButton_reset.setText("Reset");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_reset)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_tambah)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ubah))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton_laki)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_perempuan))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_nim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(jTextField_nama, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton_laki)
                    .addComponent(jRadioButton_perempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_tambah)
                    .addComponent(jButton_hapus)
                    .addComponent(jButton_ubah))
                .addGap(37, 37, 37)
                .addComponent(jButton_reset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Data Mahasiswa Informatika");

        jButton_cari.setText("Cari");

        jTable_datamahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "123", "123", "123", "Jenis Kelamin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_datamahasiswa);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_cari)
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cari)
                    .addComponent(jTextField_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cari;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_tambah;
    private javax.swing.JButton jButton_ubah;
    private javax.swing.JComboBox<String> jComboBox_jurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton_laki;
    private javax.swing.JRadioButton jRadioButton_perempuan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_datamahasiswa;
    private javax.swing.JTextField jTextField_cari;
    private javax.swing.JTextField jTextField_nama;
    private javax.swing.JTextField jTextField_nim;
    private javax.swing.ButtonGroup jenisKelamin;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton_cari() {
        return jButton_cari;
    }

    public JButton getjButton_hapus() {
        return jButton_hapus;
    }

    public JButton getjButton_reset() {
        return jButton_reset;
    }

    public JButton getjButton_tambah() {
        return jButton_tambah;
    }

    public JButton getjButton_ubah() {
        return jButton_ubah;
    }
    
    public String getNim() {
        return jTextField_nim.getText();
    }

    public void setNim(String s) {
        jTextField_nim.setText(s);
    }
    
    public String getNama() {
        return jTextField_nama.getText();
    }

    public void setNama(String s) {
        jTextField_nama.setText(s);
    }

    public String getJurusan() {
        return jComboBox_jurusan.getSelectedItem().toString();
    }

    public void setJurusan(String s) {
        jComboBox_jurusan.setSelectedItem(s);
    }
    
    public char getJeniskelamin() {
        if (jRadioButton_laki.isSelected()) {
            return 'L';
        } else {
            return 'P';
        }
    }
    
    public void setJenisKelamin(char c) {
        if (c == 'L') {
            jRadioButton_laki.setSelected(true);
            jRadioButton_perempuan.setSelected(false);
        } else {
            jRadioButton_laki.setSelected(false);
            jRadioButton_perempuan.setSelected(true);
        }
    }
    
    public String getCari() {
        return jTextField_cari.getText();
    }
    
    public void setCari(String s) {
        jTextField_cari.setText(s);
    }
    
    public void reset(){
        setNim("");
        setNama("");
        setCari("");
        setJenisKelamin('L');
        jComboBox_jurusan.setSelectedIndex(0);
    }
    
    public JTable getTableMahasiswa() {
        return jTable_datamahasiswa;
    }
    
    public void setTableMahasiswa(DefaultTableModel dtm) {
        jTable_datamahasiswa.setModel(dtm);
    }
    
    public int getSelectedMahasiswa(){
        return jTable_datamahasiswa.getSelectedRow();
    }
    
    public void addActionListener(ActionListener al) {
        jButton_tambah.addActionListener(al);
        jButton_cari.addActionListener(al);
        jButton_hapus.addActionListener(al);
        jButton_reset.addActionListener(al);
        jButton_ubah.addActionListener(al);
    }
    
    public void addMouseAdapter(MouseAdapter ma) {
        jTable_datamahasiswa.addMouseListener(ma);
    }
    
    public void showMassage(String message, String title, int type) {
        JOptionPane.showMessageDialog(null, message, title, type);
    }

}
